# Generated by Django 5.2.2 on 2025-06-07 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTypeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id_1', models.PositiveIntegerField()),
                ('object_id_2', models.PositiveIntegerField()),
                ('content_type_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_type_1', to='contenttypes.contenttype')),
                ('content_type_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_type_2', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Content Type Link',
                'verbose_name_plural': 'Content Type Links',
            },
        ),
    ]
