# Generated by Django 5.2.2 on 2025-06-07 21:04

import django.db.models.deletion
import mainapps.inventory.helpers.field_validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, help_text='User who created this model instance.', max_length=400, null=True, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('profile', models.CharField(help_text='Profile of the user or entity associated with this model.', max_length=400, verbose_name='Profile')),
                ('total_price', models.PositiveBigIntegerField(blank=True, help_text='Total price for this order', null=True, verbose_name='Total Price')),
                ('order_currency', models.CharField(blank=True, max_length=10, null=True, validators=[mainapps.inventory.helpers.field_validators.validate_currency_code], verbose_name='Order Currency')),
                ('description', models.CharField(blank=True, help_text='Order description (optional)', max_length=250, verbose_name='Description')),
                ('link', models.URLField(blank=True, help_text='Link to an external page', verbose_name='Link')),
                ('delivery_date', models.DateTimeField(blank=True, help_text='Expected date for order delivery. Order will be overdue after this date.', null=True, verbose_name='Delivery Date')),
                ('received_date', models.DateTimeField(blank=True, help_text='Date order was received', null=True, verbose_name='Received Date')),
                ('complete_date', models.DateTimeField(blank=True, help_text='Date order was completed', null=True, verbose_name='Completion Date')),
                ('responsible', models.CharField(blank=True, help_text='User or group responsible for this order', max_length=400, null=True, verbose_name='Responsible')),
                ('reference', models.CharField(help_text='Return Order reference', max_length=64, unique=True, verbose_name='Reference')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_pickup', 'Awaiting Pickup'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Return order status', verbose_name='Status')),
                ('customer_reference', models.CharField(blank=True, help_text='Customer order reference code', max_length=64, verbose_name='Customer Reference ')),
                ('issue_date', models.DateTimeField(blank=True, help_text='Date order was issued', null=True, verbose_name='Issue Date')),
                ('return_reason', models.TextField(blank=True, help_text='Detailed reason for the return', null=True, verbose_name='Return Reason')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReturnOrderLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, help_text='User who created this model instance.', max_length=400, null=True, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('quantity_returned', models.PositiveIntegerField()),
                ('return_reason', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, help_text='User who created this model instance.', max_length=400, null=True, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('profile', models.CharField(help_text='Profile of the user or entity associated with this model.', max_length=400, verbose_name='Profile')),
                ('total_price', models.PositiveBigIntegerField(blank=True, help_text='Total price for this order', null=True, verbose_name='Total Price')),
                ('order_currency', models.CharField(blank=True, max_length=10, null=True, validators=[mainapps.inventory.helpers.field_validators.validate_currency_code], verbose_name='Order Currency')),
                ('description', models.CharField(blank=True, help_text='Order description (optional)', max_length=250, verbose_name='Description')),
                ('link', models.URLField(blank=True, help_text='Link to an external page', verbose_name='Link')),
                ('delivery_date', models.DateTimeField(blank=True, help_text='Expected date for order delivery. Order will be overdue after this date.', null=True, verbose_name='Delivery Date')),
                ('received_date', models.DateTimeField(blank=True, help_text='Date order was received', null=True, verbose_name='Received Date')),
                ('complete_date', models.DateTimeField(blank=True, help_text='Date order was completed', null=True, verbose_name='Completion Date')),
                ('responsible', models.CharField(blank=True, help_text='User or group responsible for this order', max_length=400, null=True, verbose_name='Responsible')),
                ('customer_reference', models.CharField(blank=True, help_text='Customer order reference code', max_length=64, null=True, verbose_name='Customer Reference ')),
                ('shipment_date', models.DateTimeField(blank=True, null=True, verbose_name='Shipment Date')),
                ('shipped_by', models.CharField(blank=True, help_text='User or group responsible for shipping this order', max_length=400, null=True, verbose_name='Shipped By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesOrderShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, help_text='User who created this model instance.', max_length=400, null=True, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('shipment_date', models.DateField(blank=True, help_text='Date of shipment', null=True, verbose_name='Shipment Date')),
                ('delivery_date', models.DateField(blank=True, help_text='Date of delivery of shipment', null=True, verbose_name='Delivery Date')),
                ('checked_by', models.CharField(blank=True, max_length=400, null=True, verbose_name='Checked By')),
                ('reference', models.CharField(default='1', help_text='Shipment number', max_length=100, verbose_name='Shipment')),
                ('tracking_number', models.CharField(blank=True, help_text='Shipment tracking information', max_length=100, verbose_name='Tracking Number')),
                ('invoice_number', models.CharField(blank=True, help_text='Reference number for associated invoice', max_length=100, verbose_name='Invoice Number')),
                ('link', models.URLField(blank=True, help_text='Link to external page', verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, help_text='User who created this model instance.', max_length=400, null=True, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('profile', models.CharField(help_text='Profile of the user or entity associated with this model.', max_length=400, verbose_name='Profile')),
                ('total_price', models.PositiveBigIntegerField(blank=True, help_text='Total price for this order', null=True, verbose_name='Total Price')),
                ('order_currency', models.CharField(blank=True, max_length=10, null=True, validators=[mainapps.inventory.helpers.field_validators.validate_currency_code], verbose_name='Order Currency')),
                ('description', models.CharField(blank=True, help_text='Order description (optional)', max_length=250, verbose_name='Description')),
                ('link', models.URLField(blank=True, help_text='Link to an external page', verbose_name='Link')),
                ('delivery_date', models.DateTimeField(blank=True, help_text='Expected date for order delivery. Order will be overdue after this date.', null=True, verbose_name='Delivery Date')),
                ('received_date', models.DateTimeField(blank=True, help_text='Date order was received', null=True, verbose_name='Received Date')),
                ('responsible', models.CharField(blank=True, help_text='User or group responsible for this order', max_length=400, null=True, verbose_name='Responsible')),
                ('reference', models.CharField(editable=False, help_text='Order reference', max_length=64, unique=True, verbose_name='Reference')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('issued', 'Isshued'), ('completed', 'Complete'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue'), ('received', 'Received'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('lost', 'Lost'), ('returned', 'Returned')], default='pending', help_text='Purchase order status', max_length=20, verbose_name='Status')),
                ('supplier_reference', models.CharField(blank=True, help_text='Supplier order reference code', max_length=64, null=True, verbose_name='Supplier Reference')),
                ('received_by', models.CharField(blank=True, max_length=400, null=True, verbose_name='Received By')),
                ('issue_date', models.DateTimeField(blank=True, help_text='Date order was issued', null=True, verbose_name='Issue Date')),
                ('complete_date', models.DateTimeField(blank=True, help_text='Date order was completed', null=True, verbose_name='Completion Date')),
                ('workflow_state', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('SENT_TO_SUPPLIER', 'Sent to Supplier'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('FULLY_RECEIVED', 'Fully Received'), ('CLOSED', 'Closed')], default='DRAFT', max_length=50)),
                ('approval_required', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('budget_code', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('address', models.ForeignKey(blank=True, help_text='Company address for this order of the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.companyaddress', verbose_name='Address')),
                ('contact', models.ForeignKey(blank=True, help_text='Point of contact for this order, that is the person you should keep in contact with for this order in the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.contact', verbose_name='Contact Person')),
                ('supplier', models.ForeignKey(help_text='Company from which the items are being ordered', limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.company', verbose_name='Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, help_text='User who created this model instance.', max_length=400, null=True, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount rate as a percentage (e.g. 5.0)', max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount rate as a percentage (e.g. 5.0)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=18)),
                ('description', models.TextField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='orders.purchaseorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
