# Generated by Django 5.2.7 on 2026-03-12 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0002_initial'),
        ('orders', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptline',
            name='stock_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='stock.stocklocation'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Company address for this order of the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.companyaddress', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Point of contact for this order, that is the person you should keep in contact with for this order in the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.contact', verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(help_text='Company from which the items are being ordered', limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.company', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='orders.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_lines', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='orders.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderlineitem',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_line_items', to='stock.stockitem'),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='purchase_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipt_lines', to='orders.purchaseorderlineitem'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Company address for this order of the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.companyaddress', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Point of contact for this order, that is the person you should keep in contact with for this order in the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.contact', verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='customer',
            field=models.ForeignKey(help_text='Company from which items are being returned', limit_choices_to={'is_customer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.company', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_orders', to='orders.purchaseorder'),
        ),
        migrations.AddField(
            model_name='returnorderlineitem',
            name='original_line_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.purchaseorderlineitem'),
        ),
        migrations.AddField(
            model_name='returnorderlineitem',
            name='return_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='orders.returnorder'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='address',
            field=models.ForeignKey(blank=True, help_text='Company address for this order of the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.companyaddress', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Point of contact for this order, that is the person you should keep in contact with for this order in the affiliated business', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.contact', verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Company receiving the goods', limit_choices_to={'is_customer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='company.company', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='salesorderlineitem',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_lines', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='salesorderlineitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_lines', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='salesorderlineitem',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='orders.salesorder'),
        ),
        migrations.AddField(
            model_name='salesordershipment',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='salesordershipment',
            name='order',
            field=models.ForeignKey(help_text='Sales Order', on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.salesorder', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='salesordershipmentline',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_lines', to='stock.stockreservation'),
        ),
        migrations.AddField(
            model_name='salesordershipmentline',
            name='sales_order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_lines', to='orders.salesorderlineitem'),
        ),
        migrations.AddField(
            model_name='salesordershipmentline',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.salesordershipment'),
        ),
        migrations.AddField(
            model_name='salesordershipmentline',
            name='stock_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_shipment_lines', to='stock.stocklocation'),
        ),
        migrations.AddField(
            model_name='salesordershipmentline',
            name='stock_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_shipment_lines', to='stock.stocklot'),
        ),
        migrations.AddField(
            model_name='salesordershipmentline',
            name='stock_serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_shipment_lines', to='stock.stockserial'),
        ),
        migrations.AlterUniqueTogether(
            name='salesordershipment',
            unique_together={('order', 'reference')},
        ),
    ]
