# Generated by Django 5.2.2 on 2025-06-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='profile',
            field=models.CharField(blank=True, help_text='Profile of the user or entity associated with this model.', max_length=400, verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='profile',
            field=models.CharField(blank=True, help_text='Profile of the user or entity associated with this model.', max_length=400, verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='profile',
            field=models.CharField(blank=True, help_text='Profile of the user or entity associated with this model.', max_length=400, verbose_name='Profile'),
        ),
    ]
