# Generated by Django 5.2.2 on 2025-06-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Expected date for order delivery. Order will be overdue after this date.', null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Expected date for order delivery. Order will be overdue after this date.', null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Expected date for order delivery. Order will be overdue after this date.', null=True, verbose_name='Delivery Date'),
        ),
    ]
