# Generated by Django 5.2.2 on 2025-06-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_purchaseorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date order was received', null=True, verbose_name='Received Date'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date order was received', null=True, verbose_name='Received Date'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='received_date',
            field=models.DateField(blank=True, help_text='Date order was received', null=True, verbose_name='Received Date'),
        ),
    ]
