# Generated by Django 5.2.4 on 2025-07-17 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_purchaseorderlineitem_batch_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='purchase_order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='orders.purchaseorder'),
        ),
    ]
