# Generated by Django 5.2.4 on 2025-07-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_purchaseorderlineitem_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes (optional)', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes (optional)', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes (optional)', verbose_name='Notes'),
        ),
    ]
