# Generated by Django 5.2.4 on 2025-07-18 23:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_purchaseorder_notes_returnorder_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='purchaseorderlineitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderlineitem',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseorderlineitem',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='returnorder',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='orders.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='purchaseorderlineitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
