services:
  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6370"
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - intera_network
  #   restart: unless-stopped

  web:
    # image: ubongpr7/inventoryv2:latest
    image: ubongpr7/intera_users:latest

    env_file:
      - .env
    container_name: inventory-service
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        uvicorn core.asgi:application --reload --host 0.0.0.0 --port 8000
      "
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    # depends_on:
    #   - redis
    # networks:
    #   - microservice-net
    restart: unless-stopped

#   celery:
#     image: ubongpr7/inventoryv2:latest
#     env_file:
#       - .env
#     command: celery -A core worker --loglevel=info --pool=solo
#     depends_on:
#       - redis
#       - web
#     volumes:
#       - .:/app
#     networks:
#       - intera_network
#     restart: unless-stopped

# volumes:
#   redis_data:

# networks:
#   microservice-net:
#     external: true
  

