services:
  web:
    build:
      context: .
    container_name: intera-inventory
    env_file:
      - .env
    command: >
      sh -c "
        uv run manage.py makemigrations &&
        uv run manage.py migrate &&
        uv run manage.py runserver 0.0.0.0:7002
      "
    volumes:
      - .:/app
      - venv:/app/.venv
    ports:
      - "7002:7002"
    restart: unless-stopped

volumes:
  venv: