# Generated by Django 5.2.7 on 2026-03-10 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogProductProjection',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Product ID')),
                ('profile_id', models.BigIntegerField(db_index=True, verbose_name='Profile ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('category_name', models.CharField(blank=True, default='', max_length=255)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('track_stock', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['profile_id', 'is_active'], name='projections_profile_196f58_idx')],
            },
        ),
        migrations.CreateModel(
            name='CatalogVariantProjection',
            fields=[
                ('variant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Variant ID')),
                ('profile_id', models.BigIntegerField(db_index=True, verbose_name='Profile ID')),
                ('display_name', models.CharField(max_length=255, verbose_name='Display Name')),
                ('variant_name', models.CharField(blank=True, default='', max_length=255)),
                ('variant_barcode', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('variant_sku', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('image_url', models.URLField(blank=True, default='')),
                ('sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('pos_visible', models.BooleanField(db_index=True, default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='projections.catalogproductprojection')),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['profile_id', 'is_active'], name='projections_profile_9651e9_idx'), models.Index(fields=['profile_id', 'pos_visible'], name='projections_profile_1e8f66_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('variant_barcode__isnull', False)), fields=('profile_id', 'variant_barcode'), name='inv_catalog_variant_profile_barcode')],
            },
        ),
    ]
