# Generated by Django 5.2.2 on 2025-06-29 08:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('profile', models.CharField(blank=True, editable=False, help_text='Profile of the user or entity associated with this model.', max_length=400, verbose_name='Profile')),
                ('created_by', models.CharField(blank=True, editable=False, help_text='User  ID of the creator', max_length=255, null=True, verbose_name='Created By')),
                ('name', models.CharField(max_length=100, verbose_name='Company name')),
                ('description', models.CharField(blank=True, help_text='Briefly describe the company', max_length=1000, null=True, verbose_name='Company description')),
                ('website', models.URLField(blank=True, help_text='Company website URL (optional)', null=True, verbose_name='Website')),
                ('short_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number (optional)', max_length=15, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, help_text='Contact email address (optional)', max_length=254, null=True, verbose_name='Email')),
                ('link', models.URLField(blank=True, help_text='Link to external company information or profile', verbose_name='Link/Website')),
                ('is_customer', models.BooleanField(default=False, help_text='Do you sell items to this company?', verbose_name='is customer')),
                ('is_supplier', models.BooleanField(default=False, help_text='Do you purchase items from this company?', verbose_name='Is supplier')),
                ('is_manufacturer', models.BooleanField(default=False, help_text='Does this company manufacture parts?', verbose_name='is manufacturer')),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'profile'), name='unique_company_name_profile')],
            },
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, help_text='User who created this model instance.', max_length=400, null=True, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('title', models.CharField(help_text='Title describing the address entry', max_length=100, verbose_name='Address title')),
                ('address', models.CharField(max_length=300, verbose_name='Address')),
                ('primary', models.BooleanField(default=False, help_text='Set as primary or main address', verbose_name='Primary address')),
                ('shipping_notes', models.CharField(blank=True, help_text='Notes for shipping courier', max_length=100, verbose_name='Courier shipping notes')),
                ('internal_shipping_notes', models.CharField(blank=True, help_text='Shipping notes for internal use', max_length=100, verbose_name='Internal shipping notes')),
                ('link', models.URLField(blank=True, help_text='Link to address information (external)', null=True, verbose_name='Link')),
                ('company', models.ForeignKey(help_text='Select company', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='company.company', verbose_name='Company')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, help_text='User who created this model instance.', max_length=400, null=True, verbose_name='Created By')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('role', models.CharField(blank=True, help_text='Contact person role in company', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_alphanumeric', message='Only alphanumeric characters are allowed.', regex='^[a-zA-Z0-9]*$')], verbose_name='Role')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='company.company', verbose_name='Company')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
