# Generated by Django 5.2.7 on 2026-08-26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="role",
            field=models.CharField(
                blank=True,
                help_text="Contact person role in company",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_alphanumeric",
                        message="Only letters, numbers, and spaces are allowed.",
                        regex="^[a-zA-Z0-9 ]*$",
                    ),
                ],
                verbose_name="Role",
            ),
        ),
    ]
