# Generated by Django 5.2.7 on 2026-03-10 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityCompanyProfile',
            fields=[
                ('profile_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Profile ID')),
                ('company_code', models.CharField(max_length=64, unique=True, verbose_name='Company Code')),
                ('display_name', models.CharField(max_length=255, verbose_name='Display Name')),
                ('owner_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['is_active'], name='identity_id_is_acti_ebd274_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdentityUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='User ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Full Name')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['email'],
                'indexes': [models.Index(fields=['is_active'], name='identity_id_is_acti_fd3722_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdentityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Role')),
                ('permissions_json', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='identity.identitycompanyprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='identity.identityuser')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'role'], name='identity_id_profile_abce45_idx'), models.Index(fields=['user', 'is_active'], name='identity_id_user_id_09c5ee_idx')],
                'unique_together': {('profile', 'user')},
            },
        ),
    ]
