# Generated by Django 5.2.7 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="identitycompanyprofile",
            name="logo_url",
            field=models.URLField(blank=True, default="", max_length=1000, verbose_name="Company Logo URL"),
        ),
    ]
