# Generated by Django 5.2.7 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0002_identitycompanyprofile_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="identitycompanyprofile",
            name="headquarters_address",
            field=models.JSONField(blank=True, default=dict, verbose_name="Headquarters Address"),
        ),
    ]
