# Generated by Django 5.2.7 on 2026-03-22 14:49

import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brief name for the stock location type (unique)', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Longer form description of the stock location type (optional)', max_length=250, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Stock Location Type',
                'verbose_name_plural': 'Stock Location Types',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('transfer', 'Transfer')], max_length=50)),
                ('quantity_change', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('adjusted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('adjusted_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('adjusted_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('modified_by', models.CharField(blank=True, help_text='User who last modified this model instance.', max_length=400, null=True, verbose_name='Modified By')),
                ('updated_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('profile', models.CharField(blank=True, editable=False, help_text='Profile of the user or entity associated with this model.', max_length=400, verbose_name='Profile')),
                ('profile_id', models.BigIntegerField(blank=True, db_index=True, editable=False, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, help_text='User  ID of the creator', max_length=255, null=True, verbose_name='Created By')),
                ('code', models.CharField(blank=True, editable=False, help_text='Unique location identifier (auto-generated)', max_length=100, null=True, unique=True, verbose_name='Location Code')),
                ('name', models.CharField(max_length=200, null=True)),
                ('official', models.CharField(blank=True, help_text='ID of the manager for this stock location', max_length=255, null=True, verbose_name='Manager ID')),
                ('official_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('structural', models.BooleanField(default=False, help_text='Stock items may not be directly located into a structural stock location, but may be located to child locations.', verbose_name='Structural')),
                ('external', models.BooleanField(default=False, help_text='This is an external stock location', verbose_name='External')),
                ('description', models.TextField(blank=True, help_text='Longer form description of the stock location (optional)', null=True, verbose_name='Description')),
                ('physical_address', models.CharField(blank=True, max_length=255, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='The location this falls under eg if this is a sub location in a bigger location like warehouse', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='stock.stocklocation', verbose_name='Super Location')),
                ('location_type', models.ForeignKey(blank=True, help_text='Stock location type of this location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_locations', to='stock.stocklocationtype', verbose_name='Location type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.BigIntegerField(db_index=True, help_text='Identity service CompanyProfile ID.', verbose_name='Profile ID')),
                ('created_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Created By User ID')),
                ('updated_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Updated By User ID')),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Created By Name')),
                ('updated_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Updated By Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('lot_number', models.CharField(blank=True, max_length=100)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('currency_code', models.CharField(blank=True, default='', max_length=10)),
                ('received_quantity', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('remaining_quantity', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('open', 'Open'), ('quarantined', 'Quarantined'), ('depleted', 'Depleted'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('goods_receipt_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='orders.goodsreceiptline')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='inventory.inventoryitem')),
                ('purchase_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='orders.purchaseorderlineitem')),
                ('supplier', models.ForeignKey(blank=True, limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_lots', to='company.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.BigIntegerField(db_index=True, help_text='Identity service CompanyProfile ID.', verbose_name='Profile ID')),
                ('created_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Created By User ID')),
                ('updated_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Updated By User ID')),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Created By Name')),
                ('updated_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Updated By Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('quantity_on_hand', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('quantity_reserved', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('quantity_available', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='inventory.inventoryitem')),
                ('stock_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='stock.stocklocation')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_balances', to='stock.stocklot')),
            ],
        ),
        migrations.CreateModel(
            name='StockSerial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.BigIntegerField(db_index=True, help_text='Identity service CompanyProfile ID.', verbose_name='Profile ID')),
                ('created_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Created By User ID')),
                ('updated_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Updated By User ID')),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Created By Name')),
                ('updated_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Updated By Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('serial_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('issued', 'Issued'), ('damaged', 'Damaged'), ('returned', 'Returned')], db_index=True, default='available', max_length=20)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_serials', to='inventory.inventoryitem')),
                ('stock_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_serials', to='stock.stocklocation')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials', to='stock.stocklot')),
            ],
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.BigIntegerField(db_index=True, help_text='Identity service CompanyProfile ID.', verbose_name='Profile ID')),
                ('created_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Created By User ID')),
                ('updated_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Updated By User ID')),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Created By Name')),
                ('updated_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Updated By Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('external_order_type', models.CharField(max_length=50)),
                ('external_order_id', models.CharField(max_length=100)),
                ('external_order_line_id', models.CharField(blank=True, max_length=100)),
                ('reserved_quantity', models.DecimalField(decimal_places=5, max_digits=15)),
                ('fulfilled_quantity', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled'), ('released', 'Released'), ('expired', 'Expired')], db_index=True, default='active', max_length=30)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='inventory.inventoryitem')),
                ('stock_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='stock.stocklocation')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='stock.stocklot')),
                ('stock_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='stock.stockserial')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.BigIntegerField(db_index=True, help_text='Identity service CompanyProfile ID.', verbose_name='Profile ID')),
                ('created_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Created By User ID')),
                ('updated_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Updated By User ID')),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Created By Name')),
                ('updated_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Updated By Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('movement_type', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment'), ('reservation', 'Reservation'), ('release', 'Release'), ('return_in', 'Return In'), ('return_out', 'Return Out')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=15)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('reference_type', models.CharField(blank=True, default='', max_length=64)),
                ('reference_id', models.CharField(blank=True, default='', max_length=100)),
                ('actor_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='stock.stocklocation')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.inventoryitem')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='stock.stocklot')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='stock.stocklocation')),
                ('stock_serial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='stock.stockserial')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['profile_id', 'inventory_item'], name='stock_stock_profile_dd8c1b_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['profile_id', 'lot_number'], name='stock_stock_profile_42f3df_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['expiry_date'], name='stock_stock_expiry__4916e9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['profile_id', 'inventory_item', 'stock_location'], name='stock_stock_profile_6c71df_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['profile_id', 'quantity_available'], name='stock_stock_profile_3cca1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('inventory_item', 'stock_location', 'stock_lot'), name='unique_stock_balance_item_location_lot'),
        ),
        migrations.AddIndex(
            model_name='stockserial',
            index=models.Index(fields=['profile_id', 'inventory_item'], name='stock_stock_profile_d1d20b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockserial',
            index=models.Index(fields=['profile_id', 'serial_number'], name='stock_stock_profile_9ec88f_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockserial',
            constraint=models.UniqueConstraint(fields=('profile_id', 'serial_number'), name='unique_stock_serial_profile_serial_number'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['profile_id', 'external_order_type', 'external_order_id'], name='stock_stock_profile_0795bd_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreservation',
            index=models.Index(fields=['profile_id', 'status'], name='stock_stock_profile_8ce6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['profile_id', 'inventory_item', 'occurred_at'], name='stock_stock_profile_687046_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['profile_id', 'movement_type', 'occurred_at'], name='stock_stock_profile_59c8a8_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['profile_id', 'reference_type', 'reference_id'], name='stock_stock_profile_2094c6_idx'),
        ),
    ]
