# Generated by Django 5.2.7 on 2026-06-20 10:24

from django.db import migrations, models


def backfill_default_structural_locations(apps, schema_editor):
    StockLocation = apps.get_model("stock", "StockLocation")

    profile_ids = (
        StockLocation.objects.filter(profile_id__isnull=False, structural=True)
        .values_list("profile_id", flat=True)
        .distinct()
    )

    for profile_id in profile_ids:
        queryset = StockLocation.objects.filter(profile_id=profile_id, structural=True).order_by("created_at", "id")
        selected = (
            queryset.filter(is_default_structural_location=True).first()
            or queryset.filter(parent__isnull=True).first()
            or queryset.first()
        )
        if selected is None:
            continue
        queryset.exclude(id=selected.id).update(is_default_structural_location=False)
        queryset.filter(id=selected.id).update(is_default_structural_location=True)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocation',
            name='is_default_structural_location',
            field=models.BooleanField(db_index=True, default=False, help_text='Marks the structural location that should be used as the workspace default operational stock scope.', verbose_name='Default structural location'),
        ),
        migrations.RunPython(backfill_default_structural_locations, noop_reverse),
    ]
