# Generated by Django 5.2.2 on 2025-07-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='product_variant',
            field=models.CharField(blank=True, help_text='Name of the stock item', max_length=200, null=True, verbose_name='Name'),
        ),
    ]
