# Generated by Django 5.2.4 on 2025-08-05 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockitem_product_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('transfer', 'Transfer')], max_length=50)),
                ('quantity_change', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('adjusted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('adjusted_at', models.DateTimeField(auto_now_add=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='stock.stockitem')),
            ],
        ),
    ]
