# Generated by Django 5.2.7 on 2025-10-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stockadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='product_variant',
            field=models.CharField(blank=True, help_text='Barcode to variant of the product', max_length=200, null=True, verbose_name='Product Variant Barcode'),
        ),
    ]
