# Generated by Django 5.2.2 on 2025-06-23 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_inventory_unique_ipn_profile_and_more'),
        ('stock', '0004_alter_stocklocation_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.inventory'),
        ),
    ]
