# Generated by Django 5.2.7 on 2025-10-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('orders', '0008_remove_purchaseorder_total_price_and_more'),
        ('stock', '0004_alter_stockitem_product_variant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['tree_id', 'lft'], name='stock_stockitem_tree_id_lf5bb4'),
        ),
    ]
