# Generated by Django 5.2.2 on 2025-06-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockitem_ipn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='IPN',
        ),
    ]
