# Generated by Django 5.2.2 on 2025-06-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_remove_stockitem_ipn'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklocation',
            name='physical_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
