# Generated by Django 5.2.7 on 2026-03-22 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, help_text='Country of the address', max_length=255, null=True, verbose_name='Country')),
                ('region', models.CharField(blank=True, help_text='Region or state within the country', max_length=255, null=True, verbose_name='Region/State')),
                ('subregion', models.CharField(blank=True, help_text='Subregion or province within the region', max_length=255, null=True, verbose_name='Subregion/Province')),
                ('city', models.CharField(blank=True, help_text='City of the address', max_length=255, null=True, verbose_name='City')),
                ('apt_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Apartment number')),
                ('street_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Street number')),
                ('street', models.CharField(max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code', max_length=10, null=True, verbose_name='Postal code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geographical latitude of the address', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geographical longitude of the address', max_digits=9, null=True, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('modified_by', models.CharField(blank=True, help_text='User who last modified this model instance.', max_length=400, null=True, verbose_name='Modified By')),
                ('updated_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('profile', models.CharField(blank=True, editable=False, help_text='Profile of the user or entity associated with this model.', max_length=400, verbose_name='Profile')),
                ('profile_id', models.BigIntegerField(blank=True, db_index=True, editable=False, null=True)),
                ('created_by', models.CharField(blank=True, editable=False, help_text='User  ID of the creator', max_length=255, null=True, verbose_name='Created By')),
                ('structural', models.BooleanField(default=False, help_text='Inventory items may not be directly assigned to a structural category, but may be assigned to child categories.', verbose_name='Structural')),
                ('name', models.CharField(help_text='It must be unique within a tenant profile.', max_length=200, verbose_name='Category name*')),
                ('slug', models.SlugField(editable=False, max_length=230)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.BigIntegerField(db_index=True, help_text='Identity service CompanyProfile ID.', verbose_name='Profile ID')),
                ('created_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Created By User ID')),
                ('updated_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Updated By User ID')),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Created By Name')),
                ('updated_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Updated By Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('product_template_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Product Template ID')),
                ('product_variant_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Product Variant ID')),
                ('name_snapshot', models.CharField(max_length=255, verbose_name='Name Snapshot')),
                ('sku_snapshot', models.CharField(blank=True, default='', max_length=100, verbose_name='SKU Snapshot')),
                ('barcode_snapshot', models.CharField(blank=True, default='', max_length=100, verbose_name='Barcode Snapshot')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('inventory_type', models.CharField(choices=[('raw_material', 'Raw Material'), ('finished_good', 'Finished Good'), ('work_in_progress', 'Work In Progress'), ('maintenance_spare_part', 'Maintenance Spare Part'), ('consumable', 'Consumable'), ('tooling', 'Tooling'), ('packaging', 'Packaging')], default='raw_material', max_length=50, verbose_name='Inventory Type')),
                ('default_uom_code', models.CharField(blank=True, default='', max_length=32, verbose_name='Default UOM')),
                ('stock_uom_code', models.CharField(blank=True, default='', max_length=32, verbose_name='Stock UOM')),
                ('track_stock', models.BooleanField(default=True, verbose_name='Track Stock')),
                ('track_lot', models.BooleanField(default=False, verbose_name='Track Lot')),
                ('track_serial', models.BooleanField(default=False, verbose_name='Track Serial')),
                ('track_expiry', models.BooleanField(default=False, verbose_name='Track Expiry')),
                ('allow_negative_stock', models.BooleanField(default=False, verbose_name='Allow Negative Stock')),
                ('reorder_point', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('reorder_quantity', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('minimum_stock_level', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('safety_stock_level', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived'), ('discontinued', 'Discontinued')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name_snapshot'],
            },
        ),
    ]
