# Generated by Django 5.2.2 on 2025-06-29 08:02

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybatch',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stocklocation'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='default_location',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Default location for parts in this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_categories', to='stock.stocklocation', verbose_name='Default Location'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Parent to which this category falls', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.inventorycategory', verbose_name='Parent category'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Hierarchical grouping for inventory items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventories', to='inventory.inventorycategory', verbose_name='Classification Category'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stock.stockitem'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorybatch',
            unique_together={('inventory', 'batch_number')},
        ),
        migrations.AddConstraint(
            model_name='inventorycategory',
            constraint=models.UniqueConstraint(fields=('name', 'profile'), name='unique_name_profile'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['profile', 'active'], name='inventory_i_profile_b7542e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['category', 'inventory_type'], name='inventory_i_categor_ff63c0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['external_system_id'], name='inventory_i_externa_0c9e06_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['re_order_point', 'minimum_stock_level'], name='inventory_i_re_orde_0af0af_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('external_system_id', 'profile'), name='unique_inventory_external_system_id_profile'),
        ),
    ]
