# Generated by Django 5.2.7 on 2026-03-22 14:49

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('inventory', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycategory',
            name='default_location',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Default location for parts in this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_categories', to='stock.stocklocation', verbose_name='Default Location'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='Parent to which this category falls', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.inventorycategory', verbose_name='Parent category'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='default_supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_supplier': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_item_defaults', to='company.company', verbose_name='Default Supplier'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='inventory.inventorycategory', verbose_name='Inventory Category'),
        ),
        migrations.AddConstraint(
            model_name='inventorycategory',
            constraint=models.UniqueConstraint(fields=('name', 'profile'), name='unique_name_profile'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['profile_id', 'status'], name='inventory_i_profile_e2aff2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['inventory_category', 'inventory_type'], name='inventory_i_invento_70b5e8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['sku_snapshot'], name='inventory_i_sku_sna_99683a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['barcode_snapshot'], name='inventory_i_barcode_a44a51_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product_variant_id__isnull', False)), fields=('profile_id', 'product_variant_id'), name='unique_inventory_item_profile_variant'),
        ),
    ]
