# Generated by Django 5.2.2 on 2025-06-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='created_by',
            field=models.CharField(blank=True, editable=False, help_text='User  ID of the creator', max_length=255, null=True, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='created_by',
            field=models.CharField(blank=True, editable=False, help_text='User  ID of the creator', max_length=255, null=True, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='created_by',
            field=models.CharField(blank=True, editable=False, help_text='User  ID of the creator', max_length=255, null=True, verbose_name='Created By'),
        ),
    ]
