# Generated by Django 5.2.7 on 2026-06-19 19:42

import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_product_variant_image_url'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the model instance.', primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.BigIntegerField(db_index=True, help_text='Identity service CompanyProfile ID.', verbose_name='Profile ID')),
                ('created_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Created By User ID')),
                ('updated_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Updated By User ID')),
                ('created_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Created By Name')),
                ('updated_by_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Updated By Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this model instance was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this model instance was last updated.', verbose_name='Updated At')),
                ('location_name_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Location Snapshot')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('salable_override', models.BooleanField(blank=True, null=True, verbose_name='Salable Override')),
                ('purchaseable_override', models.BooleanField(blank=True, null=True, verbose_name='Purchaseable Override')),
                ('reorder_point_override', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('reorder_quantity_override', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('minimum_stock_level_override', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('safety_stock_level_override', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('allow_negative_stock_override', models.BooleanField(blank=True, null=True, verbose_name='Allow Negative Stock Override')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='inventory.inventoryitem', verbose_name='Inventory Item')),
                ('structural_location', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_placements', to='stock.stocklocation', verbose_name='Structural Location')),
            ],
            options={
                'ordering': ['inventory_item__name_snapshot', 'location_name_snapshot'],
                'indexes': [models.Index(fields=['profile_id', 'active'], name='inventory_i_profile_ed4aa8_idx'), models.Index(fields=['profile_id', 'structural_location'], name='inventory_i_profile_003ed6_idx')],
                'constraints': [models.UniqueConstraint(fields=('inventory_item', 'structural_location'), name='unique_inventory_placement_per_location')],
            },
        ),
    ]
