# Generated by Django 5.2.2 on 2025-06-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, help_text='Country of the address', max_length=255, null=True, verbose_name='Country')),
                ('region', models.CharField(blank=True, help_text='Region or state within the country', max_length=255, null=True, verbose_name='Region/State')),
                ('subregion', models.CharField(blank=True, help_text='Subregion or province within the region', max_length=255, null=True, verbose_name='Subregion/Province')),
                ('city', models.CharField(blank=True, help_text='City of the address', max_length=255, null=True, verbose_name='City')),
                ('apt_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Apartment number')),
                ('street_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Street number')),
                ('street', models.CharField(max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code', max_length=10, null=True, verbose_name='Postal code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geographical latitude of the address', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geographical longitude of the address', max_digits=9, null=True, verbose_name='Longitude')),
            ],
        ),
    ]
