# Generated by Django 5.2.2 on 2025-06-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='profile',
            field=models.CharField(blank=True, help_text='Profile of the user or entity associated with this model.', max_length=400, verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='profile',
            field=models.CharField(blank=True, help_text='Profile of the user or entity associated with this model.', max_length=400, verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='profile',
            field=models.CharField(blank=True, help_text='Profile of the user or entity associated with this model.', max_length=400, verbose_name='Profile'),
        ),
    ]
