# Generated by Django 5.2.2 on 2025-06-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_profile_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='unique_ipn_profile',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='IPN',
        ),
    ]
