# Generated by Django 5.2.2 on 2025-06-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_inventory_unique_ipn_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='holding_cost_per_unit',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='ordering_cost',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='stockout_cost',
        ),
    ]
