# Generated by Django 5.2.2 on 2025-06-24 14:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_inventory_holding_cost_per_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_type', models.CharField(choices=[('mass', 'Mass'), ('volume', 'Volume'), ('length', 'Length'), ('piece', 'Piece'), ('time', 'Time'), ('custom', 'Custom')], default='custom', help_text='Type of measurement this unit belongs to', max_length=50, verbose_name='Dimension Category')),
                ('name', models.CharField(help_text='Full name of the unit (e.g., Kilogram)', max_length=255, verbose_name='Unit Name')),
                ('abbreviated_name', models.CharField(help_text='Standard short form (e.g., kg, L, m)', max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_abbreviation', message='Abbreviation can only contain letters', regex='^[A-Za-z]+$')], verbose_name='Abbreviation')),
                ('conversion_factor', models.DecimalField(decimal_places=8, default=1.0, help_text='Conversion factor to base unit', max_digits=30)),
                ('base_unit', models.ForeignKey(blank=True, help_text='Reference to base unit for conversions', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unit', verbose_name='Base Unit')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.unit'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['dimension_type', 'name'], name='inventory_u_dimensi_b025ef_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['abbreviated_name'], name='inventory_u_abbrevi_2e4886_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('dimension_type', 'name'), name='unique_unit_per_dimension'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('abbreviated_name', 'dimension_type'), name='unique_abbreviation_per_dimension'),
        ),
    ]
