#!/usr/bin/env bash
set -euo pipefail

# Initializes Kafka topics + ACLs for the per-service SASL users.
#
# Runs inside the `acl-init` container after Kafka becomes healthy.
# Uses admin credentials generated by `init-jaas.sh` at:
#   /etc/kafka/secrets/admin.properties
#
# NOTE: All services enable idempotent producers, so every principal that produces
# must have the `IdempotentWrite` cluster ACL.

BOOTSTRAP_SERVER="${BOOTSTRAP_SERVER:-kafka:9092}"
ADMIN_PROPS="${ADMIN_PROPS:-/etc/kafka/secrets/admin.properties}"

topic_create() {
  local topic="${1:?topic required}"
  kafka-topics \
    --bootstrap-server "${BOOTSTRAP_SERVER}" \
    --command-config "${ADMIN_PROPS}" \
    --create --if-not-exists \
    --replication-factor 1 \
    --partitions 1 \
    --topic "${topic}" >/dev/null
}

acl_add_cluster() {
  local principal="${1:?principal required}"
  local operation="${2:?operation required}"
  kafka-acls \
    --bootstrap-server "${BOOTSTRAP_SERVER}" \
    --command-config "${ADMIN_PROPS}" \
    --add \
    --allow-principal "User:${principal}" \
    --operation "${operation}" \
    --cluster >/dev/null
}

acl_add_group() {
  local principal="${1:?principal required}"
  local group="${2:?group required}"
  kafka-acls \
    --bootstrap-server "${BOOTSTRAP_SERVER}" \
    --command-config "${ADMIN_PROPS}" \
    --add \
    --allow-principal "User:${principal}" \
    --operation Read \
    --operation Describe \
    --group "${group}" >/dev/null
}

acl_add_topic_ops() {
  local principal="${1:?principal required}"
  local topic="${2:?topic required}"
  shift 2
  if [[ "${#}" -eq 0 ]]; then
    echo "[ka2a-sasl] acl_add_topic_ops called without operations principal=${principal} topic=${topic}" >&2
    exit 2
  fi

  local args=()
  local op
  for op in "$@"; do
    args+=(--operation "${op}")
  done

  kafka-acls \
    --bootstrap-server "${BOOTSTRAP_SERVER}" \
    --command-config "${ADMIN_PROPS}" \
    --add \
    --allow-principal "User:${principal}" \
    "${args[@]}" \
    --topic "${topic}" >/dev/null
}

main_topics=(
  identity.user
  identity.company_profile
  identity.membership
  catalog.product
  catalog.variant
  inventory.availability
  inventory.reservation
  inventory.fulfillment
  pos.order
)

main() {
  echo "[ka2a-sasl] Creating topics (and DLQ topics)..."
  for t in "${main_topics[@]}"; do
    topic_create "${t}"
    topic_create "${t}.dlq"
  done

  echo "[ka2a-sasl] Applying cluster ACLs (IdempotentWrite)..."
  acl_add_cluster identity IdempotentWrite
  acl_add_cluster inventory IdempotentWrite
  acl_add_cluster pos IdempotentWrite
  acl_add_cluster product IdempotentWrite

  echo "[ka2a-sasl] Applying group ACLs..."
  acl_add_group identity identity-consumer
  acl_add_group inventory inventory-consumer
  acl_add_group pos pos-consumer
  acl_add_group product product-consumer

  # intera_users (identity) publishes identity.* (and may run its own consumer/consumer-side DLQ)
  echo "[ka2a-sasl] Applying topic ACLs for User:identity..."
  acl_add_topic_ops identity identity.user Describe Write Read
  acl_add_topic_ops identity identity.company_profile Describe Write Read
  acl_add_topic_ops identity identity.membership Describe Write Read
  acl_add_topic_ops identity identity.user.dlq Describe Write
  acl_add_topic_ops identity identity.company_profile.dlq Describe Write
  acl_add_topic_ops identity identity.membership.dlq Describe Write

  # intera_inventory consumes identity.*, catalog.*, pos.order; publishes inventory.*
  echo "[ka2a-sasl] Applying topic ACLs for User:inventory..."
  acl_add_topic_ops inventory identity.user Describe Read
  acl_add_topic_ops inventory identity.company_profile Describe Read
  acl_add_topic_ops inventory identity.membership Describe Read
  acl_add_topic_ops inventory catalog.product Describe Read
  acl_add_topic_ops inventory catalog.variant Describe Read
  acl_add_topic_ops inventory pos.order Describe Read
  acl_add_topic_ops inventory inventory.availability Describe Write
  acl_add_topic_ops inventory inventory.reservation Describe Write
  acl_add_topic_ops inventory inventory.fulfillment Describe Write
  # consumer-side DLQs
  acl_add_topic_ops inventory identity.user.dlq Describe Write
  acl_add_topic_ops inventory identity.company_profile.dlq Describe Write
  acl_add_topic_ops inventory identity.membership.dlq Describe Write
  acl_add_topic_ops inventory catalog.product.dlq Describe Write
  acl_add_topic_ops inventory catalog.variant.dlq Describe Write
  acl_add_topic_ops inventory pos.order.dlq Describe Write

  # product_service consumes identity.*, inventory.*; publishes catalog.*
  echo "[ka2a-sasl] Applying topic ACLs for User:product..."
  acl_add_topic_ops product identity.user Describe Read
  acl_add_topic_ops product identity.company_profile Describe Read
  acl_add_topic_ops product identity.membership Describe Read
  acl_add_topic_ops product inventory.availability Describe Read
  acl_add_topic_ops product inventory.reservation Describe Read
  acl_add_topic_ops product inventory.fulfillment Describe Read
  acl_add_topic_ops product catalog.product Describe Write
  acl_add_topic_ops product catalog.variant Describe Write
  # consumer-side DLQs
  acl_add_topic_ops product identity.user.dlq Describe Write
  acl_add_topic_ops product identity.company_profile.dlq Describe Write
  acl_add_topic_ops product identity.membership.dlq Describe Write
  acl_add_topic_ops product inventory.availability.dlq Describe Write
  acl_add_topic_ops product inventory.reservation.dlq Describe Write
  acl_add_topic_ops product inventory.fulfillment.dlq Describe Write

  # pos_backend_service consumes identity.*, catalog.*, inventory.*; publishes pos.order
  echo "[ka2a-sasl] Applying topic ACLs for User:pos..."
  acl_add_topic_ops pos identity.user Describe Read
  acl_add_topic_ops pos identity.company_profile Describe Read
  acl_add_topic_ops pos identity.membership Describe Read
  acl_add_topic_ops pos catalog.product Describe Read
  acl_add_topic_ops pos catalog.variant Describe Read
  acl_add_topic_ops pos inventory.availability Describe Read
  acl_add_topic_ops pos inventory.reservation Describe Read
  acl_add_topic_ops pos inventory.fulfillment Describe Read
  acl_add_topic_ops pos pos.order Describe Write
  # consumer-side DLQs
  acl_add_topic_ops pos identity.user.dlq Describe Write
  acl_add_topic_ops pos identity.company_profile.dlq Describe Write
  acl_add_topic_ops pos identity.membership.dlq Describe Write
  acl_add_topic_ops pos catalog.product.dlq Describe Write
  acl_add_topic_ops pos catalog.variant.dlq Describe Write
  acl_add_topic_ops pos inventory.availability.dlq Describe Write
  acl_add_topic_ops pos inventory.reservation.dlq Describe Write
  acl_add_topic_ops pos inventory.fulfillment.dlq Describe Write

  echo "[ka2a-sasl] Kafka topics + ACLs initialized successfully."
}

main "$@"
